server:
  port: 8080
  servlet:
    context-path: /identity

jpa:
  hibernate:
    ddl-auto: update
    show-sql: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shoestores
    username: root
    password: 22102005


