server:
  port: 8080
  servlet:
    context-path: /identity


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shoestores
    username: root
    password: 22102005

jpa:
  hibernate:
    ddl-auto: update
    show-sql: true

jwt :
  signerKey : "cud1yALGVgbBvbHgSwe3Gn+sIHi4/0kd5CxTquhNZ+O1Q6++lNmvzZFlKUzzMtWJ"


